//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOY_YODA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOYYODABDEntities : DbContext
    {
        public TOYYODABDEntities()
            : base("name=TOYYODABDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<correo> correo { get; set; }
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<estadoCliente> estadoCliente { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
        public virtual DbSet<tipoCliente> tipoCliente { get; set; }
        public virtual DbSet<tipoDocumento> tipoDocumento { get; set; }
    }
}
